In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import os

os.chdir("C:/PROJECTS/HOUSE PRICE PREDICTION")

In [8]:
df=pd.read_csv('Data/Housing.csv')
df.head(5)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [9]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [10]:
df.shape

(545, 13)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 69.2 KB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
#feature engineering
binary_cols=['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_cols:
    df[col]=df[col].map({'yes':1, 'no':0})

In [14]:
df= pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            545 non-null    int64
 1   area                             545 non-null    int64
 2   bedrooms                         545 non-null    int64
 3   bathrooms                        545 non-null    int64
 4   stories                          545 non-null    int64
 5   mainroad                         545 non-null    int64
 6   guestroom                        545 non-null    int64
 7   basement                         545 non-null    int64
 8   hotwaterheating                  545 non-null    int64
 9   airconditioning                  545 non-null    int64
 10  parking                          545 non-null    int64
 11  prefarea                         545 non-null    int64
 12  furnishingstatus_semi-furnished  545 non-null    bool
 13  furnishingstatus_unfurnished     545 non-null    bool
dtypes: bool(2), int64(12)
memory usage: 52.3 KB

In [16]:
bool_cols=df.select_dtypes(include='bool').columns
df[bool_cols]=df[bool_cols].astype(int)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            545 non-null    int64
 1   area                             545 non-null    int64
 2   bedrooms                         545 non-null    int64
 3   bathrooms                        545 non-null    int64
 4   stories                          545 non-null    int64
 5   mainroad                         545 non-null    int64
 6   guestroom                        545 non-null    int64
 7   basement                         545 non-null    int64
 8   hotwaterheating                  545 non-null    int64
 9   airconditioning                  545 non-null    int64
 10  parking                          545 non-null    int64
 11  prefarea                         545 non-null    int64
 12  furnishingstatus_semi-furnished  545 non-null    int64
 13  furnishingstatus_unfurnished     545 non-null    int64
dtypes: int64(14)
memory usage: 59.7 KB

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X=df.drop('price', axis=1)
X

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,7420,4,1,2,1,1,1,0,1,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,1,0,1,0,0,2,0,0,1
541,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,3620,2,1,1,1,0,0,0,0,0,0,0,1
543,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,3850,3,1,2,1,0,0,0,0,0,0,0,1

In [20]:
y=df['price']
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor

In [24]:
models={
    "Linear Regression": LinearRegression(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
    "Random Forest Regressor": RandomForestRegressor()
}
result=[]

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_error, r2_score
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred= model.predict(X_test_scaled)
    MAE= mean_absolute_error(y_test, y_pred)
    RMSE= np.sqrt(mean_squared_error(y_test, y_pred))
    R2= r2_score(y_test, y_pred)

    result.append({
        "Model": name,
        "Mean Absolute Error": MAE,
        "Root Mean Squared Error": RMSE,
        "R2 Score": R2
        
    })

In [26]:
result

[{'Model': 'Linear Regression',
  'Mean Absolute Error': 970043.4039201644,
  'Root Mean Squared Error': np.float64(1324506.9600914407),
  'R2 Score': 0.6529242642153174},
 {'Model': 'Gradient Boosting Regressor',
  'Mean Absolute Error': 961029.0276228299,
  'Root Mean Squared Error': np.float64(1299213.968203335),
  'R2 Score': 0.666053323447169},
 {'Model': 'Random Forest Regressor',
  'Mean Absolute Error': 1004122.5094801224,
  'Root Mean Squared Error': np.float64(1384443.0228616432),
  'R2 Score': 0.6208020879854887}]

In [27]:
import joblib
joblib.dump(models['Gradient Boosting Regressor'], 'Models/house_price_model.pkl')
joblib.dump(scaler, 'Models/house_price_scaler.pkl')
joblib.dump(X.columns.tolist(), 'Models/house_price_features.pkl')

['Models/house_price_features.pkl']

In [30]:
new_house = pd.DataFrame([{
    'area':                              3000,
    'bedrooms':                          3,
    'bathrooms':                         2,
    'stories':                           2,
    'mainroad':                          1,   # ← was missing (1=yes, 0=no)
    'guestroom':                         0,   # ← was missing
    'basement':                          0,   # ← was missing
    'hotwaterheating':                   0,   # ← was missing
    'airconditioning':                   1,   # ← was missing
    'prefarea':                          1,   # ← was missing
    'parking':                           1,
    'furnishingstatus_semi-furnished':   0,
    'furnishingstatus_unfurnished':      1
}])

# Align columns
new_house = new_house[features]

# Scale and predict
new_house_scaled    = scaler.transform(new_house)
predicted_price     = model.predict(new_house_scaled)

print(f"Predicted Price: {predicted_price[0]:,.0f}")

Predicted Price: 5,299,031